---
apiVersion: v1
kind: Pod
metadata:
  name: foofi
  labels:
    name: foofi
spec:
  containers:
  - name: foofi
    image: gcr.io/third-pen-318122/foofi:latest
    env:
      - name: MY_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
    ports:
    - containerPort: 3000
      name: react
---
apiVersion: v1
kind: Service
metadata:
  name: foofi-service
spec:
  type: LoadBalancer
  selector:
    name: foofi
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30950 # range(30000-32767)